{
 "title": "쿠버네티스 클러스터 모니터링",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~'$Namespace'}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$Namespace Namespace Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$Pod Pod CPU 사용률",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$Namespace\", pod=~\"$Pod\", container!=\"\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "$Pod Pod 메모리 사용량",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$Pod\", namespace=~\"$Namespace\", container!=\"\", container!=\"POD\"}) by (pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "API 서버 응답 시간(5분/SLA 99%)",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod 상태",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"$Pod\", namespace=~\"$Namespace\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "노드 CPU 사용률",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "노드 메모리 사용량",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_Active_bytes", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "노드 네트워크 평균 송수신 트래픽",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(node_network_transmit_bytes_total[5m])) by (node)",
     "legendFormat": "{{node}}-transmit"
    },
    {
     "expr": "avg(rate(node_network_receive_bytes_total[5m])) by (node) * -1",
     "legendFormat": "{{node}}-receive"
    }
   ]
  },
  {
   "title": "노드 상태",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"kubernetes-nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}