apiVersion: v1
kind: Pod
metadata:
  name: efs-write-app
spec:
  containers:
  - name: efs-write-app
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo EFS Kubernetes Static Provisioning Test $(date -u) >> /data/efs-static.txt; sleep 5; done"]
    volumeMounts:
    - mountPath: "/data"
      name: persistent-storage
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim